### ISSUE TITLE
Serial Interface with Rev E

### ISSUE THREAD

**Issue by sammer-h** [OLIMEX/ESP32-GATEWAY#12]
Hello.

First I used Rev B for an application which needs two serial ports.
One for communication with an other device, the second for flash and monitor and CLI.

But with Rev E Uart2 is not usable because Pin 17 is clock output for  ETH
and Pins for Uart1 seem to be used for internal purpose.

Is there any solution for this problem.

Thank for any ideas.

**Comment by DanKoloff** [comment]
You can configure another pin for UART2. What environment do you use?

**Comment by sammer-h** [comment]
Thank you for the fast reply.
I found the answer in the documentation, too.
Enviroment: Linux with newest esp-idf.

**Comment by DanKoloff** [comment]
Glad you got it going. Closing the issue as solved.
