### ISSUE TITLE
Revision F hardware

### ISSUE THREAD

**Issue by ArendJan** [OLIMEX/ESP32-GATEWAY#17]
I recently bought a esp32 gateway revision F, but I am unable to find the correct schematics for that revision. 
At least the pinout is different, but are there any other changes?

**Comment by DanKoloff** [comment]
There are major changes in the hardware design. Differences to the pins at the GPIO header, 1-bit SD card mode now implemented, a lot of improvements for the power consumption during sleep and deep sleep! Added 3D view in the design files. I've added the resources and the differences now.

**Comment by ArendJan** [comment]
Thanks!
