### ISSUE TITLE
I2S codec?

### ISSUE THREAD

**Issue by serjepatoff** [OLIMEX/ESP32-GATEWAY#19]
Not an issue, just a question.

Is it possible to attach i2s audio in/out codec to ESP32-GATEWAY without clocking and pin assignment conflicts with EMAC? Something like Cirrus/Wolfson WM8731 audio ADC/DAC?

**Comment by DanKoloff** [comment]
Sure, it seems the I2S function can be set to free GPIOs:

https://docs.espressif.com/projects/esp-idf/en/v4.2/esp32/api-reference/peripherals/i2s.html
