### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Tangerino** [OLIMEX/ESP32-GATEWAY#21]
Several broken links in the section "upper level" at 
```url
https://github.com/OLIMEX/ESP32-GATEWAY/tree/master/SOFTWARE/Newest-board-revisions/ESP32_Gateway_Ethernet_v4.0
```

**Comment by DanKoloff** [comment]
Thanks, it is fixed now. The README was copy-pasted from the original demo code and never properly edited.
