### ISSUE TITLE
Ethernet support

### ISSUE THREAD

**Issue by Tangerino** [OLIMEX/ESP32-GATEWAY#22]
Just added a week ago, the documentation at:
```url
https://github.com/OLIMEX/ESP32-GATEWAY/tree/master/SOFTWARE/Newest-board-revisions/ESP32_Gateway_Ethernet_v4.0
```

Is not correct, there is no support for LAN8720 in the SDK.

Also how to make it work with the GPIO0/17 clock mode since it was removed from the sdk v4?

**Comment by DanKoloff** [comment]
What? If you mean the README.md it seems it only explains ESP32-EVB, but no real mention of ESP32-GATEWAY. Will look into it.
