### ISSUE TITLE
Cant find "Use LAN8720" in "Support SPI to Ethernet Module" and then in that submenu check 

### ISSUE THREAD

**Issue by joshuacv** [OLIMEX/ESP32-GATEWAY#26]
I am using esp-idf to flash the ESP32_Gateway_Ethernet_v4.0 to an Olimex-ESP32-gateway. I followed the instructions and at menuconfig step, I did not find the LAN8720 module in the "support SPI to ethernet module" submenu. 

Any ideas?

**Comment by DanKoloff** [comment]
What is the exact version of ESP-IDF that you use?

**Comment by malandles** [comment]
Both v4.4.4 and v5.0.1 do not have that option anymore.

**Comment by DanKoloff** [comment]
Example configuration - Internal EMAC - Ethernet PHY device - LAN87xx
