### ISSUE TITLE
Ethernet not working properly?

### ISSUE THREAD

**Issue by magnifikus** [OLIMEX/ESP32-GATEWAY#3]
Trying to get the Gateway up with the ESP32-EVB PHY Example
1. i need to enable the layer 2->3 copy in the phy settings or i get emac rx error!! on every packet on ethernet
2. the board is not getting any dhcp address, sniffing the ethernet i not even see an outgoing dhcp request

any ideas?

**Comment by DanKoloff** [comment]
The IDF changed and this issue appeared. Until we fix it, use the workaround provided by user "wobaekat" in the forums: https://www.olimex.com/forum/index.php?topic=5891.0

**Comment by DanKoloff** [comment]
The examples had been updated and should work properly with the latest ESP-IDF without problems.
