### ISSUE TITLE
Not receiving DHCP after hard reset and soft reboot on screen

### ISSUE THREAD

**Issue by Smeedy** [OLIMEX/ESP32-GATEWAY#4]
First off, nice work. I'm really fond of the design as we need a board to operate as a gateway in an industrial environment where WiFi is not an option. I'm testing a specimen of the rev-b which works ok'ish, but is seems a little flaky. Hope this is a case of change-user.

When I build the ethernet example from the IDF (v3.1-dev-84-gf8bda324) and use the following options I get an IP
```
#
# Example Configuration
#
CONFIG_PHY_TLK110=
CONFIG_PHY_LAN8720=y
CONFIG_PHY_ADDRESS=0
CONFIG_PHY_CLOCK_GPIO0_IN=y
CONFIG_PHY_CLOCK_GPIO0_OUT=
CONFIG_PHY_CLOCK_GPIO16_OUT=
CONFIG_PHY_CLOCK_GPIO17_OUT=
CONFIG_PHY_CLOCK_MODE=0
CONFIG_PHY_USE_POWER_PIN=
CONFIG_PHY_SMI_MDC_PIN=23
CONFIG_PHY_SMI_MDIO_PIN=18
```
But something is off as it seems. When I do a power cycle or a hard button reset, it fails to get an IP from the DHCP server (loops 0.0.0.0). When I do a `make monitor` or the trusted `screen /dev/cu.wchusbserial1410 115200` the device does a soft reboot and then I get an IP in the second loop and everything is fine.

What am I missing?

**Comment by DanKoloff** [comment]
I can't say exactly but some suggestions that might help you debug the issue. Are you trying to get IP from Ethernet or WIFI DHCP server? Does this happen sometimes or every time? Have you tried with another piece of network equipment (can it be related to the DHCP server)? Can you try using the Arduno example (this might be the easiest way to determine if it is purely software issue)?
