### ISSUE TITLE
Gateway bluetooth - wifi / lan example with mqtt

### ISSUE THREAD

**Issue by Netoperz** [OLIMEX/ESP32-GATEWAY#6]
Is it possible to get a demo sketch for arduino, that will use gateway board as BLE serial <==> wifi/lan gateway ?

i would like to see the bluetooth wifi lan running in tasks in arduino ide.

DO You have any suggestions how to do that ?

**Comment by DanKoloff** [comment]
Doesn't look like an issue to me.
