### ISSUE TITLE
ble scan performance?

### ISSUE THREAD

**Issue by 4nte** [OLIMEX/ESP32-GATEWAY#8]
Are there any testing results with this gateway? I'm specifically interested in how much BLE devices can be scanned in a 2-5 second interval.
I have my own esp32 gateway which only scans 10-30beacons in 2sec scanning period, while there is 60+ beacons nearby. 

** If I disable WIFI, the BT scan works perfectly, this is a known ESP32 problem.

**Comment by DanKoloff** [comment]
The BLE is part of the ESP32 module and performance is pretty much the same as advertised by espressif. You should check for the specs in this official FAQ file here: https://www.espressif.com/sites/default/files/documentation/ESP32_FAQs__EN.pdf
